# Generated by Django 4.2.3 on 2023-07-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person'),
        ),
        migrations.AddField(
            model_name='liked',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person'),
        ),
        migrations.AddField(
            model_name='liked',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
